### ISSUE TITLE
Base库依赖问题

### ISSUE THREAD

**Issue by qinghua0706** [SheTieJun/clingLib#1]
你好！base_version = "e6276eeadd" 这个版本号对应的库好像找不到了，现在项目运行不起来，可以帮忙更新下吗，谢谢了！

**Comment by SheTieJun** [comment]
> 你好！base_version = "e6276eeadd" 这个版本号对应的库好像找不到了，现在项目运行不起来，可以帮忙更新下吗，谢谢了！

这个库实现的功能很少的，如果你是为公司APP集成，去用乐播sdk。免费的

**Comment by qinghua0706** [comment]
好的，谢谢！
