### ISSUE TITLE
ClingDLNAManager.startLocalFileService(this)无法使用

### ISSUE THREAD

**Issue by AchievoZhou** [SheTieJun/clingLib#2]

**Comment by SheTieJun** [comment]
测试了一下，没有问题，当前项目主要是为了自己的业务功能，如果有需求请自行修改，不提供解决方案

**Comment by AchievoZhou** [comment]
你好，本地投屏时一直提示获取网络数据失败,拼接地址如下所示http://168.11.***.***:8888/clingLocaleFile/storage/emulated/0/DCIM/FaceMe/2023102507.mp4
