### ISSUE TITLE
请问不能用Cling library2.1.2的原因是什么？

### ISSUE THREAD

**Issue by qiusunshine** [SheTieJun/clingLib#3]
看到文档说Cling library 只能使用2.1.1 ，当2.1.2时无法搜索到设备，请问有研究过具体是哪里的代码有问题导致不能用2.1.2吗？

因为我一直有类似问题，就是有时候有些设备搜索不到或者搜索很慢，但原因不太清楚，不知道是不是和这个版本有关，如果你有研究过能否告知一下呢？期待回复

**Comment by SheTieJun** [comment]
1.  2.1.2搜索有问题，这个应该是代码逻辑问题，具体什么原因有点久忘记，也有可能是需要设置什么，但是我不知道。
2.  有时候有些设备搜索不到或者搜索很慢，这里你需要明白Cling基于的协议，
     - 有些设备搜索不到可能是因为用的不是UPnP协议。所以才有电视端的投屏软件，比如乐播等等，他们会有的多种协议，甚至会自定义协议。
     - 搜索很慢，这个我觉得大部分是正常现象，因为我们调用**搜索**的时候向默认多播 IP 和端口发送获取信息，这是**基于协议发送一个UDP消息**，如果有设备接收到这个消息就会响应，问题就在可能丢包，亦或者你发送的时机不对~。
     - 我没写过电视端接受端，所有更多情况我也不太知道

**Comment by qiusunshine** [comment]
感谢回复。不过之前遇到的问题其实是偶现的，比如之前好好用，但是某天开始一直搜不到，或者强制重新搜多试几次等一阵又可以了，或者重试也搜不到，因为这样的问题有不少用户反馈，所以感觉它有点问题，但我又不容易复现，因此一直在想能不能优化，又无从下手



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月17日(周日) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SheTieJun/clingLib] 请问不能用Cling library2.1.2的原因是什么？ (Issue #3)




  
2.1.2搜索有问题，这个应该是代码逻辑问题，具体什么原因有点久忘记，也有可能是需要设置什么，但是我不知道。
 
有时候有些设备搜索不到或者搜索很慢，这里你需要明白Cling基于的协议，  
有些设备搜索不到可能是因为用的不是UPnP协议。所以才有电视端的投屏软件，比如乐播等等，他们会有的多种协议，甚至会自定义协议。
 
搜索很慢，这个我觉得大部分是正常现象，因为我们调用搜索的时候向默认多播 IP 和端口发送获取信息，这是基于协议发送一个UDP消息，如果有设备接收到这个消息就会响应，问题就在可能丢包，亦或者你发送的时机不对~。
 
我没写过电视端接受端，所有更多情况我也不太知道
