### ISSUE TITLE
投放失败:Error: Not enough iN args, too many IN args, no iN arg by that name, one ormore iN args are of the wrong data type. CurrentURi can not be null or malformed.(HTTP response was: 500 Internal Server Error)

### ISSUE THREAD

**Issue by cgzwyy** [SheTieJun/clingLib#4]
投放失败:Error: Not enough iN args, too many IN args, no iN arg by that name, one ormore iN args are of the wrong data type. CurrentURi can not be null or malformed.(HTTP response was: 500 Internal Server Error)

投的是市面上的一个 AndroidTV 那种大屏，报这个错，大神怎么解决这个

**Comment by SheTieJun** [comment]
额，我不知道你啥情况啊~  我也不一定能解决，我用的电视一直是小米~，你可以从下面的问题做一下分析
1. 你是否正常连接到设备了吗？投放的媒体类型是什么？是否是媒体有问题？
2. 如果投的是本地的文件，如果使用的是我这个库，你必须一直打开app才行，因为我的服务器在是APP上运行的。
3.  如果投的是线上的，投放的url是什么？投放的其他url是否正常？看错误，好像获取的这个链接有问题，然后调用的时候服务器返回了500

**Comment by cgzwyy** [comment]
连接成功了，投放失败了，播放的是本地的一个mp4文件，本地播放是没问题的，估计资源应该没问题
APP一直打开的，我投到小米上是没问题的，不过客户那边用的是一个智能广告机就报这个错
我再研究研究吧，感谢您的回复

**Comment by SheTieJun** [comment]
可以尝试断点一下 服务器模块接受请求部分，看下广告机是否发送过了正常的请求
![image](https://github.com/SheTieJun/clingLib/assets/17263560/950171c0-efd1-4aea-93d2-94780681f9b8)
