### ISSUE TITLE
非常感谢您的项目，运行了之后网络url是正常播放的，但是本地视频有的可以正常播放，有的没有任何反应，都是mp4视频，时间可以读取到，但是不会播放

### ISSUE THREAD

**Issue by aicareles** [SheTieJun/clingLib#6]

**Comment by SheTieJun** [comment]
没有视频，所以我只能猜测。
首先我说一下这个库Cling目前是没人维护的，然后构建本地服务器也是基于它以前依赖的库，所以我不知道超大的Mp4会不会有问题.
![image](https://github.com/SheTieJun/clingLib/assets/17263560/0f4a57ef-cf98-4ea7-bb27-adca46603dd7)

**然后有的可以播放，说明我的代码是没有问题，所以问题只有可能出在视频上面了**
所以可能我这里猜测有2个原因：
1. 有些MP4编码有问题，电视不支持，你可以尝试重新编码MP4
2. 构建本地服务器库因为太老，导致不支持超大的Mp4，你可以尝试把setContentLength 这一行代码去掉后再试试。
