### ISSUE TITLE
感谢昨天你的建议，把文件长度去掉可以播放了，但是要等很久，但有的视频可以立马播放，所以还是不清楚到底什么原因呢

### ISSUE THREAD

**Issue by aicareles** [SheTieJun/clingLib#7]

**Comment by SheTieJun** [comment]
这里涉及多个方面的问题，可能还有视频编码问题了，我音视频编码能力只是初级，又没有对应的视频，所以也只能告诉你一些尝试方法。昨天按我的方法修改成功播放，看来的确是你的文件太大了。

我能给到尝试的建议有2个：
1. 优化视频，你可以搜索一下视频秒播的优化文章，播放慢出现的本质原因就是首帧出现太慢了。以前又看过一遍不错的文章，可惜我忘记关键字了，搜索不到了。（怀疑你的视频是直播合并的那种不是非常标准的视频，以前好像又遇到类似的问题，但是忘记如何处理了）
2. 昨天删除代码的地方把buff读取改大一点，加快传输的速度，但是可能应该优化效果不大。

最后后面问题我应该帮助不了什么了。

**Comment by aicareles** [comment]
> 这里涉及多个方面的问题，可能还有视频编码问题了，我音视频编码能力只是初级，又没有对应的视频，所以也只能告诉你一些尝试方法。昨天按我的方法修改成功播放，看来的确是你的文件太大了。
> 
> 我能给到尝试的建议有2个：
> 1. 优化视频，你可以搜索一下视频秒播的优化文章，播放慢出现的本质原因就是首帧出现太慢了。以前又看过一遍不错的文章，可惜我忘记关键字了，搜索不到了。（怀疑你的视频是直播合并的那种不是非常标准的视频，以前好像又遇到类似的问题，但是忘记如何处理了）
> 2. 昨天删除代码的地方把buff读取改大一点，加快传输的速度，但是可能应该优化效果不大。
> 
> 最后后面问题我应该帮助不了什么了。
非常感谢您的回复，感觉第一种方式比较合理，播放慢的视频确实都是经过ffmpeg处理后的视频，如果正常拍摄或者下载的视频是比较快的，那应该是视频的问题，我先搜下看如何解决

**Comment by aicareles** [comment]
今天看了下日志，视频不能播放的时候会报403![IMG_20240615_210933232.jpg](https://github.com/SheTieJun/clingLib/assets/18432469/c76a6204-2b1b-45bc-bcca-20898ffb083e)

**Comment by SheTieJun** [comment]
关于403 这个问题 ，可能是因为文件实际长度和contentLength不一样导致的。这里设计http相关原理和这个老版本jetty的实现原理。
如果不介意包变大，你可以自己实现本地服务器这个流程。网上有很多类似的库。
普通的时候contengLength是可以不写。
Content-Length如果需要存在且生效，他的值必须是正确的，否则会发生异常。(大于实际值会超时，小于实际值会截断并可能导致后续的数据解析混乱)

**Comment by SheTieJun** [comment]
> 非常感谢您的回复，感觉第一种方式比较合理，播放慢的视频确实都是经过ffmpeg处理后的视频，如果正常拍摄或者下载的视频是比较快的，那应该是视频的问题，我先搜下看如何解决

可以看下这篇文章
[十亿级视频播放技术优化揭密](https://cloud.tencent.com/developer/article/1006282)

![VUVPIREE}BCFY$CZ)4@Z31M](https://github.com/SheTieJun/clingLib/assets/17263560/f1f6250e-d10a-4bf1-8da2-123cf338b662)

**如果是ffmpeg的话可以试试： -movflags +faststart**
